[context.production.environment]
CMS_URL_PROD = "https://bernstein.dev"

[context.dev.environment]
CMS_URL_PROD = "https://dev.bernstein.dev"

[context.staging.environment]
CMS_URL_PROD = "https://staging.bernstein.dev"
