[context.production.environment]
CMS_URL_PROD = "https://cms.bernstein.dev"

[context.dev.environment]
CMS_URL_PROD = "https://cms-dev.bernstein.dev"

[context.internal.environment]
CMS_URL_PROD = "https://cms-internal.bernstein.dev"
