[context.production.environment]
CMS_URL = "https://cms.bernstein.dev"

[context.dev.environment]
CMS_URL = "https://cms-dev.bernstein.dev"

[context.staging.environment]
CMS_URL = "https://cms-staging.bernstein.dev"
